### ISSUE TITLE
Promote version 0.11 from 0.11.0rc1

### ISSUE THREAD

**Issue by pombredanne** [package-url/packageurl-python#112]
I pushed a version 0.11.0rc1 that can be used to test on PyPI.
@madpah @TG1999 @gruebel your feedback is mucho welcomed.

If you can kick in the tires a little, we will then promote 0.11.0rc1 to 0.11.0

**Comment by gruebel** [comment]
nice, thanks! will try it out in our project

**Comment by tdruez** [comment]
v0.11.1 released https://github.com/package-url/packageurl-python/releases/tag/v0.11.1
