### ISSUE TITLE
Provide support for Gitlab versioning

### ISSUE THREAD

**Issue by DennisClark** [package-url/packageurl-python#133]
A recent scan of hoppr-v1.11.1-dev.2.tar.gz  downloaded from https://gitlab.com/hoppr/hoppr/-/archive/v1.11.1-dev.2/hoppr-v1.11.1-dev.2.tar.gz  produced a reasonably accurate scan but the purl values are missing the Version.  It appears that the somewhat complex version of a Gitlab package is not being understood.  Scan results attached. 

[hoppr-v1.11.1-dev.2.tar.gz_scan.json.zip](https://github.com/package-url/packageurl-python/files/13562177/hoppr-v1.11.1-dev.2.tar.gz_scan.json.zip)

**Comment by tdruez** [comment]
Added in https://github.com/package-url/packageurl-python/pull/134
