### ISSUE TITLE
Fix the macos "Python CI / Test & build" failures

### ISSUE THREAD

**Issue by tdruez** [package-url/packageurl-python#160]
For example:

```
  Upgrading pip...
  Error: dyld[3297]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    Referenced from: <07D5E0A7-E19C-3D8F-B269-121F5EE9FF07> /Users/runner/hostedtoolcache/Python/3.
  Error: 10.14/x64/bin/python3.10
    Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
  ./setup.sh: line 54:  3297 Abort trap: 6           ./python -m ensurepip
  Error: The process '/bin/bash' failed with exit code 134
```

**Comment by tdruez** [comment]
```
Test & build (py3.7 on macos-latest)
The version '3.7' with architecture 'arm64' was not found for macOS 14.5.
```

The CI is using `macos-latest` which is macOS 14 and is based on arm64. Python 3.7 is not supported on that architecture.

The short-term fix is to force `macos-13` in the CI but it's time to reconsider Python 3.7 support.

Python 3.7 is not officially supported anymore https://devguide.python.org/versions/#versions
I think we should drop active support in this library as well.

@pombredanne any thoughts on this?

**Comment by pombredanne** [comment]
@tdruez we should drop Python 3.7 alright. This is a really dead snake by now.  As for macOS versions, for this library, one is enough.

**Comment by tdruez** [comment]
https://github.com/package-url/packageurl-python/pull/163
