### ISSUE TITLE
[NPM] get_purl returns None if the input is a URLs with 3 path segments: namespace, name, version

### ISSUE THREAD

**Issue by jloehel** [package-url/packageurl-python#167]
https://github.com/package-url/packageurl-python/blob/04a706abb512ee4c8a8be30c573e9a09e003a18c/src/packageurl/contrib/url2purl.py#L146-L147

Something like this, with 3 path segments, is also possible: `https://registry.npmjs.org/@esbuild/freebsd-arm64/0.21.5`

**Input:** `https://registry.npmjs.org/@esbuild/freebsd-arm64/0.21.5`
**Returns:** `None`
**Expected:** `pkg:npm/%40esbuild/freebsd-arm64@0.21.5`

**Comment by tdruez** [comment]
@jloehel I've added support for 3 path segments URLs in https://github.com/package-url/packageurl-python/pull/170

It's available in the latest release at https://github.com/package-url/packageurl-python/releases/tag/v0.16.0
