### ISSUE TITLE
Add support for Rust Packages

### ISSUE THREAD

**Issue by TG1999** [package-url/packageurl-python#23]
Currently their is no support for Rust Packages (crates) in package-url python repo

**Comment by TG1999** [comment]
I will like to work on this issue

**Comment by pombredanne** [comment]
Do we want to call these crates vs. rust vs cargo?
The spec states to use cargo https://github.com/package-url/purl-spec/blob/84e9bd8f952a4fa513ea1ecc9fb4ba9eb259e885/README.rst#L707

**Comment by TG1999** [comment]
Hi, @pombredanne https://doc.rust-lang.org/cargo/ in this it is told that crates.io is the registry for cargo packages

**Comment by TG1999** [comment]
Closed via #24
