### ISSUE TITLE
npm url2purl should handle more npm package url schemes

### ISSUE THREAD

**Issue by majurg** [package-url/packageurl-python#38]
Current implementation: https://github.com/package-url/packageurl-python/blob/00b7df61173be3c19eb65ce166271aed0e9ae00c/src/packageurl/contrib/url2purl.py#L82

We need to support more npm package url schemes, such as:
* https://www.npmjs.com/package/foo-utils
* https://yarnpkg.com/package/foo

**Comment by tdruez** [comment]
Thanks @scovetta, really nice contribution.
