### ISSUE TITLE
Using Black for formatting of code

### ISSUE THREAD

**Issue by TG1999** [package-url/packageurl-python#52]
Currently no code formatter is not used in packageurl-python, so a suggestion to add black for code formatting .

**Comment by aditirao7** [comment]
Can I work on this?

**Comment by TG1999** [comment]
Sure!!

**Comment by TG1999** [comment]
I think pre commit would be better, @pombredanne suggestions on this ?

**Comment by aditirao7** [comment]
After reading some more about pre-commits, I realised they are mostly for local repositories. So I think everyone who clones the repo will have to run `pre-commit install` to activate it. Correct me if I am wrong but if this is the case then maybe a github action will be required too?

**Comment by pombredanne** [comment]
@aditirao7 do you still want to do this?

**Comment by pombredanne** [comment]
In all cases pre-commit or not this (a black check) should also be a standard tests that fails when running the test suite (including locally)

**Comment by aditirao7** [comment]
> @aditirao7 do you still want to do this?

Yes, I'm sorry for the delay. Will send in a PR now.
