### ISSUE TITLE
ImportError: No module named packageurl

### ISSUE THREAD

**Issue by srinivasmachiraju** [package-url/packageurl-python#6]
In the test_purl.py the from the statement in line 31 no path is set to find the file packageurl.py so  its showing the error 
![error](https://user-images.githubusercontent.com/30867734/35779677-164dab66-09c9-11e8-9bd3-2f6a8f765e68.png)

`

**Comment by haikoschol** [comment]
@srinivasmachiraju Please run the tests as described in the [README](https://github.com/package-url/packageurl-python/blob/7fde9e5a48a0745b10d58ed1ccd1bb03b6c0155f/README.rst): `py.test -vvs`

Also make sure you have not only the test dependencies installed in a virtualenv, but also the project itself, in "editable" mode: `pip install -e .`.
For the time being, please use Python 2.7. The code should work with Python 3 as well but I just had the tests fail and believe it is a unicode vs byte string issue.

**Comment by pombredanne** [comment]
Closing since there has been no reply and activity.
