### ISSUE TITLE
`setup.py` install is deprecated. Use build and pip and other standards-based tools

### ISSUE THREAD

**Issue by madpah** [package-url/packageurl-python#85]
`setuptools` install is deprecated and a warning regarding this is displayed during this project's current build process:

```
> python setup.py build sdist bdist_wheel
...
running bdist_wheel
/Users/phorton/Documents/GitHub/madpah/packageurl-python/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
...
```

I would suggest that this project adopts a more modern package manager such as [Poetry](https://python-poetry.org/).

@pombredanne - do you have thoughts on this?

**Comment by pombredanne** [comment]
@madpah  I am not sure that this deprecation is a big deal as this is used internally by setuptools. That said, I am OK to move to `build` which can be done now without changing anything and works fine as-is for with the current setup configuration.

But I am NOT OK to use Poetry. My reasons are that:
- I do not want to promote more fragmentation in Python packaging: there is plenty enough of it and I want to stick to PyPA and PSF-supported tools as much as possible, excluding Pipfile which I consider as a failed experiment.
- I also do not like several of the Poetry ways and I think this is not a good choice for a library:
  - it introduces new files formats
  - it specifies a new and different syntax and semantics for dependencies and version ranges beyond the already messy https://peps.python.org/pep-0440/#version-specifiers. AFAIK, this is the only tool with this wart in the Python world.
  - it promotes systematically an upper version bound on deps using its own made-up syntax derived from node-semver which is creating a long term disservice for the consumers of libraries built with Poetry.  See https://iscinumpy.dev/post/bound-version-constraints/  and https://github.com/python-poetry/poetry/issues/2731 for some background on the topic

**Comment by tdruez** [comment]
The warning is gone with the upgrade of virtualenv.pyz in https://github.com/package-url/packageurl-python/commit/455b94b15a65c2c6f341cbbc3ece6ed1334820a6

Closing as we do no plan to keep the current package management implementation.
